# Generated by Django 4.2.6 on 2023-10-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_item_category_remove_item_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueitem',
            name='issued_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
