# Generated by Django 4.2.6 on 2023-10-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_issueitem_issued_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueitem',
            name='issued_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
