# Generated by Django 4.2.6 on 2023-10-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_issueitem_issued_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='issueitem',
            name='issued_to',
            field=models.CharField(max_length=120),
        ),
    ]
