# Generated by Django 4.2.6 on 2023-10-07 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_issueitem_selling_price_alter_issueitem_issued_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueitem',
            name='issued_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.customer'),
        ),
    ]
